### PR TITLE
options fix

### PR DESCRIPTION
**Pull request by cpena**
When an option is **0** or **false** in
`const value = options[key] || this.options[key];`
always get the default option (this.options[key])

### CODE REVIEW

**Comment by dlukanin** [comment]
Thx for pull request! I ll check it and merge soon

**Comment by dlukanin** [comment]
Hi there! There is no need to commit and push js files - they are auto generated before each release by typescript compiler

**Comment by cpena** [comment]
Hi!, Ok, I was need to commit the js files to test my code from github, it's my first PR :-)

**Comment by dlukanin** [comment]
Thank you for metion this issue in PR. I've fixed it in the last library release.

**Pull request closed without merging**
